In [1]:
import numpy as np

A = np.array([1, 2, 3, 4])
print A
print A.shape
print A.dtype

[1 2 3 4]
(4,)
int64


In [2]:
B = np.array([
    [1.1, 2.1, 3.1],
    [4.1, 5.1, 6.1]
])
print B
print B.shape
print B.dtype

[[ 1.1  2.1  3.1]
 [ 4.1  5.1  6.1]]
(2, 3)
float64


In [3]:
print np.arange(4)
print np.arange(4).reshape(2, 2)
print np.zeros(4).reshape(2, 2)
print np.arange(8).reshape(2, 2, 2)

[0 1 2 3]
[[0 1]
 [2 3]]
[[ 0.  0.]
 [ 0.  0.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [4]:
A = np.arange(start=1, step=1, stop=5).reshape(2, 2)
B = np.ones(4).reshape(2, 2)
B[0][0] = 0

print A * 2
print A * B
print A.dot(B)

[[2 4]
 [6 8]]
[[ 0.  2.]
 [ 3.  4.]]
[[ 2.  3.]
 [ 4.  7.]]


In [5]:
A = np.random.random((3, 1))
print A
A = np.random.randint(low=50, high=100, size=(2, 2))
print A
print A.sum(), A.min(), A.max(), A.mean(), A.std(), A.argmax()
print A.sum(axis=0), A.min(axis=1)
print np.sqrt(A)

[[ 0.53902228]
 [ 0.13386045]
 [ 0.86478057]]
[[64 96]
 [55 82]]
297 55 96 74.25 15.8804124632 1
[119 178] [64 55]
[[ 8.          9.79795897]
 [ 7.41619849  9.05538514]]


In [6]:
A = np.array([1, 2, 3, 4], dtype='float64').reshape(2, 2)
print A
print A.transpose()
I = np.eye(2)
print I
print A.dot(I)
A_inv = np.linalg.inv(A)
print A_inv
print np.linalg.solve(A, I)
print A.trace()

[[ 1.  2.]
 [ 3.  4.]]
[[ 1.  3.]
 [ 2.  4.]]
[[ 1.  0.]
 [ 0.  1.]]
[[ 1.  2.]
 [ 3.  4.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[-2.   1. ]
 [ 1.5 -0.5]]
5.0


In [7]:
x = np.array([8, 8])
y = np.array([7 ,7])
print np.vstack([x, y])
print np.hstack([x, y])
# More details : https://docs.scipy.org/doc/numpy/reference/routines.html

[[8 8]
 [7 7]]
[8 8 7 7]
