In [21]:
import numpy as np

A = np.array([1, 2, 3, 4])
print A
print A.shape
print A.dtype
print type(A)

[1 2 3 4]
(4,)
int64
<type 'numpy.ndarray'>


In [22]:
B = np.array([
    [1.1, 2.1, 3.1],
    [4.1, 5.1, 6.1]
])
print B
print B.shape
print B.dtype

[[ 1.1  2.1  3.1]
 [ 4.1  5.1  6.1]]
(2, 3)
float64
<type 'numpy.ndarray'>


In [3]:
print np.arange(4)
print np.arange(4).reshape(2, 2)
print np.zeros(4).reshape(2, 2)
print np.arange(8).reshape(2, 2, 2)

[0 1 2 3]
[[0 1]
 [2 3]]
[[ 0.  0.]
 [ 0.  0.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [4]:
A = np.arange(start=1, step=1, stop=5).reshape(2, 2)
B = np.ones(4).reshape(2, 2)
B[0][0] = 0

print A * 2
print A * B
print A.dot(B)

[[2 4]
 [6 8]]
[[ 0.  2.]
 [ 3.  4.]]
[[ 2.  3.]
 [ 4.  7.]]


In [20]:
A = np.random.random((3, 1))
print A
A = np.random.randint(low=50, high=100, size=(2, 2))
print A
print A.sum(), A.min(), A.max(), A.mean(), A.std(), A.argmax()
print A.sum(axis=0), A.min(axis=1)
print np.sqrt(A)
print A.flatten()
A.sort()
print A
print A.diagonal()

[[ 0.37057988]
 [ 0.41510975]
 [ 0.50947502]]
[[97 98]
 [91 54]]
340 54 98 85.0 18.0969610709 1
[188 152] [97 54]
[[ 9.8488578   9.89949494]
 [ 9.53939201  7.34846923]]
[97 98 91 54]
[[97 98]
 [54 91]]
[97 91]
[ 0.  0.  0.  0.  0.]
[ 3.  3.  3.  3.  3.]


In [6]:
A = np.array([1, 2, 3, 4], dtype='float64').reshape(2, 2)
print A
print A.T
I = np.eye(2)
print I
print A.dot(I)
A_inv = np.linalg.inv(A)
print A_inv
print np.linalg.solve(A, I)
print A.trace()

[[ 1.  2.]
 [ 3.  4.]]
[[ 1.  3.]
 [ 2.  4.]]
[[ 1.  0.]
 [ 0.  1.]]
[[ 1.  2.]
 [ 3.  4.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[-2.   1. ]
 [ 1.5 -0.5]]
5.0


In [7]:
x = np.array([8, 8])
y = np.array([7 ,7])
print np.vstack([x, y])
print np.hstack([x, y])
# More details : https://docs.scipy.org/doc/numpy/reference/routines.html

[[8 8]
 [7 7]]
[8 8 7 7]


In [39]:
import pandas as pd

print pd.Series(np.arange(10))
print pd.date_range('2017-06-01', periods=7)
df = pd.DataFrame(np.arange(25).reshape(5,5), columns=['A', 'B', 'C', 'D', 'E'])
print df
print df[['A','C']]
df[['A', 'C']] = df[['C', 'A']]
print df
print df[df['A'] > 10]
print df[(df['A'] > 10) & (df['C'] < 15)]

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64
DatetimeIndex(['2017-06-01', '2017-06-02', '2017-06-03', '2017-06-04',
               '2017-06-05', '2017-06-06', '2017-06-07'],
              dtype='datetime64[ns]', freq='D')
    A   B   C   D   E
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24
    A   C
0   0   2
1   5   7
2  10  12
3  15  17
4  20  22
    A   B   C   D   E
0   2   1   0   3   4
1   7   6   5   8   9
2  12  11  10  13  14
3  17  16  15  18  19
4  22  21  20  23  24
    A   B   C   D   E
2  12  11  10  13  14
3  17  16  15  18  19
4  22  21  20  23  24
    A   B   C   D   E
2  12  11  10  13  14


In [46]:
dates = pd.date_range('2017-06-01', periods=7)
df = pd.DataFrame(np.random.randint(low=100, high=300, size=(7, 3)), index=dates, columns=[u'早餐', u'午餐', u'晚餐'])
print df
print df.sum()

             早餐   午餐   晚餐
2017-06-01  222  163  126
2017-06-02  226  178  107
2017-06-03  104  139  222
2017-06-04  205  196  256
2017-06-05  228  169  168
2017-06-06  268  280  138
2017-06-07  268  126  115
早餐    1521
午餐    1251
晚餐    1132
dtype: int64
