In [6]:
import numpy as np

a = np.array([1, 2, 3, 4])
print a
print a.shape
print a.dtype

[1 2 3 4]
(4,)
int64


In [7]:
b = np.array([
    [1.1, 2.1, 3.1],
    [4.1, 5.1, 6.1]
])
print b
print b.shape
print b.dtype

[[ 1.1  2.1  3.1]
 [ 4.1  5.1  6.1]]
(2, 3)
float64


In [12]:
print np.arange(4)
print np.arange(4).reshape(2, 2)
print np.zeros(4).reshape(2, 2)

[0 1 2 3]
[[0 1]
 [2 3]]
[[ 0.  0.]
 [ 0.  0.]]
